name: Terraform Cost

on:
  workflow_call:
    secrets:
          admin_account_id:
            description: the account id of secret storage
          role_name:
            description: the oidc provider role

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  infracost-pull-request-checks:
    name: Infracost Pull Request Checks
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    steps:
        - name: AWS Login - Management Environment
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ secrets.admin_account_id }}:role/${{ secrets.role_name }}
            aws-region: us-east-1
            
        - name: Set API Key
          id: set_api_key
          shell: bash
          run: |
            INFRACOST_API_KEY=$(aws ssm get-parameter --name "The-Wild-West-InfraCost-APIKey" | jq -r '.Parameter.Value')
            echo "infracost_api_key=$INFRACOST_API_KEY" >> "$GITHUB_OUTPUT"
        - name: Setup Infracost
          uses: infracost/actions/setup@v3
          with:
           api-key: ${{ steps.set_api_key.outputs.infracost_api_key }}

        - name: Checkout base branch
          uses: actions/checkout@v4
          with:
            ref: '${{ github.event.pull_request.base.ref }}'

        - name: Generate Infracost cost estimate baseline
          run: |
            infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost-base.json

        - name: Checkout PR branch
          uses: actions/checkout@v4

        - name: Generate Infracost diff
          run: |
            infracost diff --path=. \
                          --format=json \
                          --compare-to=/tmp/infracost-base.json \
                          --out-file=/tmp/infracost.json
                
            cat /tmp/infracost.json
            
            # Show diff in logs for debugging
            infracost diff --path=. \
                          --compare-to=/tmp/infracost-base.json

            cat /tmp/infracost-base.json
      # Posts a comment to the PR using the 'update' behavior.
      # This creates a single comment and updates it. The "quietest" option.
      # The other valid behaviors are:
      #   delete-and-new - Delete previous comments and create a new one.
      #   hide-and-new - Minimize previous comments and create a new one.
      #   new - Create a new cost estimate comment on every push.
      # See https://www.infracost.io/docs/features/cli_commands/#comment-on-pull-requests for other options.
        - name: Post Infracost comment
          run: |
            infracost comment github --path=/tmp/infracost.json \
                                     --repo=$GITHUB_REPOSITORY \
                                     --github-token=${{ github.token }} \
                                     --pull-request=${{ github.event.pull_request.number }} \
                                     --behavior=update

  # Run Infracost on default branch and update Infracost Cloud
